{"name": "test_sample2", "status": "failed", "statusDetails": {"message": "AssertionError: assert 5 == 6", "trace": "def test_sample2():\n>       assert 5 == 6\nE       assert 5 == 6\n\nPythonAPI\\test_API005.py:14: AssertionError"}, "start": 1702447787501, "stop": 1702447787502, "uuid": "4ec6cf4d-145f-4bd7-ad1f-7bc1c269aad2", "historyId": "cea2f82a2a7b7374d15ec0a2b4eeec33", "testCaseId": "cea2f82a2a7b7374d15ec0a2b4eeec33", "fullName": "PythonAPI.test_API005#test_sample2", "labels": [{"name": "parentSuite", "value": "PythonAPI"}, {"name": "suite", "value": "test_API005"}, {"name": "host", "value": "DESKTOP-HP3DQ6Q"}, {"name": "thread", "value": "968-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "PythonAPI.test_API005"}]}